djangonautic/articles/urls.py
from django.urls import path
from django.conf.urls import url

from . import views
app_name = 'articles'

urlpatterns = [
    url(r'^$', views.article_list, name='list'),
    url(r'^(?P<slug>[\w-]+)/$',views.article_detail, name='detail'),
]

djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/',include('articles.urls')),
    url(r'^about/$', views.about),
    url(r'^$', views.homepage),
]

urlpatterns += staticfiles_urlpatterns()

djangonautic/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    #add in thumbnail and author later on
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + "..."

djangonautic/articles/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Article

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles':articles})

def article_detail(request,slug):
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article})

djangonautic/djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def about(request):
    return render(request, 'about.html')

def homepage(request):
    return render(request, 'homepage.html')

djangonautic/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}
{% block content%}
<div class="article_detail">
  <div class="article">
    <h2>{{article.title}}</h2>
    <p>{{article.body}}</p>
    <p>{{article.date}}</p>
  </div>
</div>
{% endblock %}

djangonautic/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% block content%}
    <h1>Article List</h1>
    <div class="articles">
      {% for article in articles %}
      <div class="article">
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
        <p>{{article.snippet}}</p>
        <p>{{article.date}}</p>
      </div>
      {% endfor %}
    </div>
{% endblock %}

djangonautic/templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>About us</h1>
    <p>We like Django</p>
  </body>
</html>

djangonautic/templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Articles</title>
    <link rel="stylesheet" href="{%static 'styles.css'%}">
  </head>
  <body>
    <div class="wrapper">
      <h1><a href="{% url 'articles:list' %}"><img src="{% static 'logo.png' %}"></a></h1>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

djangonautic/templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
  </head>
  <body>
    <h1>This is the homepage</h1>
    <p>Welcome to Djangonautic</p>
  </body>
</html>